import Link from "next/link";

// Privacy page (spec section 1, surface S4). Honest statement of what is
// stored and sent. No server-side data beyond what is listed here.

export const metadata = {
  title: "Privacy — Bitget rVue",
};

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-2xl px-6 py-16">
      <h1 className="text-2xl font-semibold text-text">Privacy</h1>

      <div className="mt-6 space-y-5 text-sm leading-relaxed text-muted">
        <section>
          <h2 className="font-medium text-text">What we store</h2>
          <p className="mt-1">
            Conversations are stored entirely in your browser&apos;s local
            storage under the key <code className="font-mono text-xs">rvue.chats.v1</code>.
            Nothing is sent to any server except the messages you actively submit
            to the research endpoint. We do not use cookies or analytics trackers.
          </p>
        </section>

        <section>
          <h2 className="font-medium text-text">What we send</h2>
          <ul className="mt-1 list-disc pl-5 space-y-1">
            <li>
              <strong>Bitget public API v2</strong> — rToken symbols, tickers,
              and coin metadata. No authentication or user data is transmitted.
            </li>
            <li>
              <strong>Yahoo Finance v8 chart API</strong> — equity quotes for
              underlying tickers. Public, unauthenticated requests.
            </li>
            <li>
              <strong>Blockscout v2</strong> — token holder counts and recent
              transfers from ArbitrumOne. Public block explorer API.
            </li>
            <li>
              <strong>Qwen via the Bitget hackathon endpoint</strong> — when you
              request a research brief, your question and a compacted Evidence
              Package (market data, not personal data) are sent to the
              qwen3.8-max model. The model response is streamed back and
              displayed. No conversation history is sent — each request is
              stateless.
            </li>
            <li>
              <strong>RSS news providers</strong> — Google News and Yahoo Finance
              RSS feeds are fetched server-side for headline context. No user
              data is included in these requests.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="font-medium text-text">What we do not do</h2>
          <ul className="mt-1 list-disc pl-5 space-y-1">
            <li>We do not execute trades or connect to exchange accounts.</li>
            <li>We do not collect, store, or transmit personal information.</li>
            <li>We do not use third-party analytics, tracking pixels, or advertising.</li>
            <li>We do not retain server-side logs of your questions or conversations.</li>
          </ul>
        </section>

        <section>
          <h2 className="font-medium text-text">AI-generated content</h2>
          <p className="mt-1">
            Research briefs are generated by Qwen 3.8-Max and are advisory
            only. Every number displayed in the UI is computed deterministically
            from API responses — the AI model interprets but never produces
            figures. All claims are tagged by kind (FACT, COMPUTED,
            INTERPRETATION, UNKNOWN) and citations are verified against the
            Evidence Package.
          </p>
        </section>

        <section>
          <h2 className="font-medium text-text">Not investment advice</h2>
          <p className="mt-1">
            Bitget rVue is a research tool. Nothing on this site constitutes
            financial, investment, or trading advice. All data is provided for
            informational purposes only.
          </p>
        </section>
      </div>

      <div className="mt-10 border-t border-border pt-5">
        <Link
          href="/rtokens"
          className="text-sm text-muted hover:text-text transition-colors"
        >
          ← Back to the board
        </Link>
      </div>
    </div>
  );
}
