"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ThemeToggle } from "@/lib/ui/theme";
import { Icon } from "@/components/ui/Icon";
import { ArrowRight } from "lucide-react";
import type { ScanSummary } from "@/lib/scanner/scan";

import { Hero } from "@/components/landing/Hero";
import { BoardPreview } from "@/components/landing/BoardPreview";
import { ProblemSection } from "@/components/landing/ProblemSection";
import { Pipeline } from "@/components/landing/Pipeline";
import { EvidenceDiscipline } from "@/components/landing/EvidenceDiscipline";
import { Guarantees } from "@/components/landing/Guarantees";

export default function MarketingHome() {
  const [scan, setScan] = useState<ScanSummary | null>(null);
  const [scanLoading, setScanLoading] = useState(true);

  useEffect(() => {
    async function fetchScan() {
      try {
        const res = await fetch("/api/scan");
        if (res.ok) {
          const data = await res.json();
          setScan(data);
        }
      } catch (err) {
        console.error("Scan fetch error:", err);
      } finally {
        setScanLoading(false);
      }
    }
    void fetchScan();
  }, []);

  return (
    <div className="relative min-h-screen flex flex-col bg-bg text-text selection:bg-brand/20">
      {/* Top Navbar */}
      <header className="sticky top-0 z-40 border-b border-glass-border bg-surface/75 backdrop-blur-md">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-brand/15 border border-brand/30 shadow-xs">
              <span className="font-mono text-sm font-bold tracking-tighter text-brand">
                Br
              </span>
            </div>
            <div className="flex flex-col">
              <span className="font-mono text-sm font-bold tracking-tight text-text">
                Bitget rVue
              </span>
              <span className="font-mono text-[10px] text-tertiary uppercase tracking-widest">
                7x24 Research Desk
              </span>
            </div>
          </div>

          <nav className="hidden md:flex items-center gap-6 text-xs font-medium text-muted">
            <Link href="#problem" className="hover:text-text transition-colors">
              The 24/7 Gap
            </Link>
            <Link href="#pipeline" className="hover:text-text transition-colors">
              Pipeline
            </Link>
            <Link href="#evidence" className="hover:text-text transition-colors">
              Evidence Discipline
            </Link>
            <Link href="/rtokens" className="hover:text-text transition-colors">
              Live Board
            </Link>
          </nav>

          <div className="flex items-center gap-3">
            <ThemeToggle />
            <Link
              href="/chat"
              className="inline-flex items-center gap-1.5 rounded-lg bg-brand px-3.5 py-1.5 text-xs font-semibold text-accent-contrast shadow-xs hover:bg-brand/90 transition-colors"
            >
              <span>Launch Desk</span>
              <Icon icon={ArrowRight} size={13} />
            </Link>
          </div>
        </div>
      </header>

      <main className="flex-1">
        <Hero scan={scan} scanLoading={scanLoading} />
        <BoardPreview scan={scan} />
        <ProblemSection />
        <Pipeline />
        <EvidenceDiscipline />
        <Guarantees />
      </main>

      {/* FOOTER */}
      <footer className="border-t border-border bg-surface/70 py-10 px-4 sm:px-6 lg:px-8 text-xs text-muted">
        <div className="mx-auto max-w-7xl flex flex-col sm:flex-row justify-between items-center gap-4">
          <div className="flex items-center gap-2">
            <span className="font-mono font-bold text-text">Bitget rVue</span>
            <span>•</span>
            <span>Built for Bitget AI Hackathon S2</span>
          </div>

          <div className="flex items-center gap-4 text-tertiary">
            <span>Bitget API</span>
            <span>•</span>
            <span>Yahoo Finance</span>
            <span>•</span>
            <span>Blockscout</span>
            <span>•</span>
            <span>Qwen 3.8-Max</span>
          </div>
        </div>

        <div className="mx-auto max-w-7xl mt-6 pt-6 border-t border-border/50 text-[11px] text-tertiary text-center sm:text-left">
          Disclaimer: Bitget rVue is strictly an advisory research workbench. No automated trade execution exists. All data is provided for informational and analytical purposes only and does NOT constitute investment or financial advice. Research briefs are generated by artificial intelligence (Qwen 3.8-Max) and may contain errors. Always verify citations against the original sources.
        </div>
      </footer>
    </div>
  );
}