import fs from "node:fs";
import path from "node:path";
import { fetch as undiciFetch, type Response as UndiciResponse } from "undici";
import { dohModelAgent } from "../net/doh";

// qwen3.8-max is strictly restricted to signal reasoning, structured JSON data
// extraction from Evidence Packages, and macro event summarization.
// There is NO autonomous execution pipeline in Bitget rVue. All trading actions
// or signals generated by the model terminate in a "Research Brief" view that
// requires explicit human review and execution.

const DEFAULT_BASE_URL = `${process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'}/api/bitget-proxy`;
const DEFAULT_MODEL = "qwen3.8-max";
const DEFAULT_TIMEOUT_MS = 300000;
const DEFAULT_TEMPERATURE = 0.2;
const DEFAULT_MAX_TOKENS = 2200;

export type ModelErrorCode =
  | "MODEL_NOT_CONFIGURED"
  | "MODEL_HTTP_ERROR"
  | "MODEL_TIMEOUT"
  | "MODEL_EMPTY_RESPONSE"
  | "MODEL_INVALID_JSON";

export class ModelError extends Error {
  readonly code: ModelErrorCode;
  readonly detail: string;

  constructor(code: ModelErrorCode, detail: string) {
    super(code + ": " + detail);
    this.name = "ModelError";
    this.code = code;
    this.detail = detail;
  }
}

export interface QwenConfig {
  apiKey: string | null;
  baseUrl: string;
  model: string;
  timeoutMs: number;
  temperature: number;
  maxTokens: number;
  jsonResponseFormat: boolean;
}

interface ChatMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

interface ChatCompletionResponse {
  id?: string;
  model?: string;
  choices?: Array<{ message?: { content?: string | null } | null; finish_reason?: string | null } | null> | null;
  usage?: { prompt_tokens?: number; completion_tokens?: number; total_tokens?: number } | null;
  message?: string;
  code?: string;
}

interface StreamEvent {
  model?: string;
  choices?: Array<{
    delta?: { content?: string | null } | null;
    message?: { content?: string | null } | null;
    finish_reason?: string | null;
  } | null> | null;
  usage?: { prompt_tokens?: number; completion_tokens?: number; total_tokens?: number } | null;
}

export interface CompletionResult {
  parsed: unknown;
  text: string;
  model: string;
  finishReason: string | null;
  usage: { promptTokens: number | null; completionTokens: number | null; totalTokens: number | null };
  durationMs: number;
}

function envInt(name: string, fallback: number): number {
  const raw = process.env[name];
  if (raw === undefined || raw.trim() === "") return fallback;
  const parsed = Number.parseInt(raw, 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

function envFloat(name: string, fallback: number): number {
  const raw = process.env[name];
  if (raw === undefined || raw.trim() === "") return fallback;
  const parsed = Number.parseFloat(raw);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function envFlag(name: string, fallback: boolean): boolean {
  const raw = process.env[name];
  if (raw === undefined || raw.trim() === "") return fallback;
  return !["0", "false", "no", "off"].includes(raw.trim().toLowerCase());
}

export function getModelConfig(): QwenConfig {
  const apiKey = process.env.QWEN_API_KEY?.trim() || process.env.DASHSCOPE_API_KEY?.trim() || null;
  const baseUrl = (process.env.QWEN_BASE_URL?.trim() || DEFAULT_BASE_URL).replace(/\/+$/, "");
  return {
    apiKey: apiKey && apiKey.length > 0 ? apiKey : null,
    baseUrl,
    model: process.env.QWEN_MODEL?.trim() || DEFAULT_MODEL,
    timeoutMs: envInt("QWEN_TIMEOUT_MS", DEFAULT_TIMEOUT_MS),
    temperature: envFloat("QWEN_TEMPERATURE", DEFAULT_TEMPERATURE),
    maxTokens: envInt("QWEN_MAX_TOKENS", DEFAULT_MAX_TOKENS),
    jsonResponseFormat: envFlag("QWEN_RESPONSE_FORMAT", true),
  };
}

export function isModelConfigured(): boolean {
  return getModelConfig().apiKey !== null;
}

export function describeModelConfig(): { configured: boolean; baseUrl: string; model: string; keyPreview: string } {
  const config = getModelConfig();
  const key = config.apiKey ?? "";
  return {
    configured: config.apiKey !== null,
    baseUrl: config.baseUrl,
    model: config.model,
    keyPreview: key.length === 0 ? "(unset)" : key.slice(0, 4) + "..." + key.slice(-2),
  };
}

export function extractJsonObject(text: string): string {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  const candidate = fenced ? fenced[1] : text;
  const start = candidate.indexOf("{");
  const end = candidate.lastIndexOf("}");
  if (start < 0 || end <= start) return candidate.trim();
  return candidate.slice(start, end + 1).trim();
}

export interface CompleteJsonOptions {
  system: string;
  user: string;
  temperature?: number;
  maxTokens?: number;
  timeoutMs?: number;
}

export async function completeJson(options: CompleteJsonOptions): Promise<CompletionResult> {
  const config = getModelConfig();
  if (config.apiKey === null) {
    throw new ModelError(
      "MODEL_NOT_CONFIGURED",
      "Set QWEN_API_KEY (or DASHSCOPE_API_KEY) to enable the research brief. Optionally set QWEN_BASE_URL and QWEN_MODEL.",
    );
  }

  const messages: ChatMessage[] = [
    { role: "system", content: options.system },
    { role: "user", content: options.user },
  ];
  const body: Record<string, unknown> = {
    model: "qwen3.8-max",
    messages,
    stream: true,
    temperature: options.temperature ?? config.temperature,
    max_tokens: options.maxTokens ?? config.maxTokens,
  };
  if (config.jsonResponseFormat) body.response_format = { type: "json_object" };

  const startedAt = Date.now();
  let response: UndiciResponse;
  try {
    response = await undiciFetch(config.baseUrl + "/chat/completions", {
      dispatcher: dohModelAgent,
      method: "POST",
      headers: {
        authorization: "Bearer " + config.apiKey,
        "content-type": "application/json",
        accept: "text/event-stream",
        "user-agent": "rvue-research/1.0",
      },
      body: JSON.stringify(body),
      signal: AbortSignal.timeout(options.timeoutMs ?? config.timeoutMs),
    });
  } catch (err) {
    const cause = err instanceof Error && err.cause != null ? (err.cause instanceof Error ? err.cause.message : String(err.cause)) : "";
    const message = String(err instanceof Error ? err.message : err) + (cause ? " | cause: " + cause : "");
    const code: ModelErrorCode = /timeout|aborted|ETIMEDOUT/i.test(message) ? "MODEL_TIMEOUT" : "MODEL_HTTP_ERROR";
    throw new ModelError(code, message.slice(0, 400));
  }

  if (!response.ok) {
    let preview = "";
    try { preview = (await response.text()).slice(0, 300); } catch { preview = ""; }
    throw new ModelError("MODEL_HTTP_ERROR", "HTTP " + response.status + " from " + config.baseUrl + "/chat/completions - " + preview);
  }

  const contentType = response.headers.get("content-type") ?? "";
  let text = "";
  let model = config.model;
  let finishReason: string | null = null;
  let usage = { promptTokens: null as number | null, completionTokens: null as number | null, totalTokens: null as number | null };

  if (contentType.includes("text/event-stream")) {
    const decoder = new TextDecoder();
    let buffer = "";
    try {
      for await (const chunk of response.body as unknown as AsyncIterable<Uint8Array>) {
        buffer += decoder.decode(chunk, { stream: true });
        let newlineIndex;
        while ((newlineIndex = buffer.indexOf("\n")) >= 0) {
          const line = buffer.slice(0, newlineIndex).replace(/\r$/, "");
          buffer = buffer.slice(newlineIndex + 1);
          if (!line.startsWith("data:")) continue;
          const payload = line.slice(5).trim();
          if (payload.length === 0 || payload === "[DONE]") continue;
          let event: StreamEvent;
          try { event = JSON.parse(payload) as StreamEvent; } catch { continue; }
          if (event.model) model = event.model;
          const choice = event.choices?.[0];
          const delta = choice?.delta?.content ?? choice?.message?.content;
          if (typeof delta === "string") text += delta;
          if (choice?.finish_reason) finishReason = choice.finish_reason;
          if (event.usage) {
            usage = {
              promptTokens: event.usage.prompt_tokens ?? null,
              completionTokens: event.usage.completion_tokens ?? null,
              totalTokens: event.usage.total_tokens ?? null,
            };
          }
        }
      }
    } catch (err) {
      const cause = err instanceof Error && err.cause != null ? (err.cause instanceof Error ? err.cause.message : String(err.cause)) : "";
      const message = String(err instanceof Error ? err.message : err) + (cause ? " | cause: " + cause : "");
      const code: ModelErrorCode = /timeout|aborted|ETIMEDOUT/i.test(message) ? "MODEL_TIMEOUT" : "MODEL_HTTP_ERROR";
      throw new ModelError(code, message.slice(0, 400));
    }
  } else {
    let full: ChatCompletionResponse;
    try {
      full = (await response.json()) as ChatCompletionResponse;
    } catch (err) {
      throw new ModelError("MODEL_INVALID_JSON", "could not parse non-stream response: " + String(err instanceof Error ? err.message : err));
    }
    const choice = full.choices?.[0];
    text = choice?.message?.content ?? "";
    model = full.model ?? config.model;
    finishReason = choice?.finish_reason ?? null;
    usage = {
      promptTokens: full.usage?.prompt_tokens ?? null,
      completionTokens: full.usage?.completion_tokens ?? null,
      totalTokens: full.usage?.total_tokens ?? null,
    };
    if (text.trim().length === 0) {
      const upstream = full.message ?? full.code ?? "no content returned";
      throw new ModelError("MODEL_EMPTY_RESPONSE", String(upstream).slice(0, 300));
    }
  }

  if (text.trim().length === 0) {
    throw new ModelError("MODEL_EMPTY_RESPONSE", "stream returned no content");
  }

  const jsonText = extractJsonObject(text);
  let parsed: unknown;
  try {
    parsed = JSON.parse(jsonText);
  } catch (err) {
    try {
      fs.mkdirSync(path.join(process.cwd(), ".cache"), { recursive: true });
      fs.writeFileSync(path.join(process.cwd(), ".cache", "last-model-output.txt"), text, "utf8");
    } catch { /* diagnostics are best-effort */ }
    throw new ModelError("MODEL_INVALID_JSON", "could not parse model output as JSON: " + String(err instanceof Error ? err.message : err) + " - preview: " + jsonText.slice(0, 300));
  }

  return {
    parsed,
    text,
    model,
    finishReason,
    usage,
    durationMs: Date.now() - startedAt,
  };
}